feat: Don/avatars
UCLA-Creative-Labs/lab pull request #21
Opened 2020-12-14 22:56 UTC by BryanPan342

@DonLe27

2020-12-14 22:57 UTC, BryanPan342 reviewed
plox remove autostyle

2020-12-14 22:57 UTC, BryanPan342 commented on server/src/index.js
>  const socketIo = require('socket.io');
plox turn off ur auto style LMAO

2020-12-15 01:38 UTC, arjunr00 requested changes

2020-12-15 01:38 UTC, arjunr00 commented on server/src/index.js
> -const port = process.env.PORT || 3000;
put this back pls lmao

2020-12-16 04:56 UTC, closed without merging

2020-12-16 04:56 UTC, DonLe27 commented
Superseding this branch with don/dogs pr