New Avatar
UCLA-Creative-Labs/lab pull request #27
Opened 2020-12-16 05:00 UTC by DonLe27

It's a shiba
Bug: Can't sit on the couches

2020-12-16 05:04 UTC, DonLe27 commented
TODO: the face disappears if you look at the shiba from a certain angle. I'll fix it after Thursday but if you have any ideas please comment lmao

2020-12-18 06:40 UTC, BryanPan342 commented on server/src/index.js
> +const dotenv = require('dotenv');
remove this change

2020-12-18 06:44 UTC, BryanPan342 requested changes
remove changes:
- server/src/index.js

remove files:
- **/steve.*
- assets/test.glb

only changes i need to hit merge

2020-12-18 06:44 UTC, BryanPan342 commented on server/src/index.js
> +const dotenv = require('dotenv');
remove this change

2020-12-18 06:44 UTC, BryanPan342 commented on client/src/assets/steve.obj
> +# Blender v2.74 (sub 0) OBJ File: ''
remove this file

2020-12-18 06:55 UTC, BryanPan342 approved these changes
LGTM

2020-12-18 06:55 UTC, merged