feat: Add project names above images + put in actual slides
UCLA-Creative-Labs/lab pull request #33
Opened 2020-12-18 21:16 UTC by DonLe27

2020-12-18 21:46 UTC, BryanPan342 requested changes
@DonLe27 remove changes to server/src/index.js and remove the test.glb file

2020-12-18 21:46 UTC, BryanPan342 commented on server/src/index.js
> +const dotenv = require('dotenv');
remove this change

2020-12-18 23:36 UTC, DonLe27 commented on server/src/index.js
> +const dotenv = require('dotenv');
done thanks

2020-12-19 01:16 UTC, arjunr00 submitted a review, later dismissed
lgtm

2020-12-19 02:11 UTC, josephtclegg reviewed
looks like we're off to the races

2020-12-19 02:14 UTC, BryanPan342 approved these changes

2020-12-19 02:18 UTC, merged